backend: 
  name: github
  repo: persephonepunch/yslgatsby
  
media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: content/sample-posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }